# Configuration to monitor linux system status.

new-session -d -s monitor -n system "top"
split-window -v -t monitor:system "nvidia-smi dmon -s pucm"

new-window -t monitor -n network "mtr -t 1.1.1.1"
split-window -v -t monitor:network "gping 1.1.1.1"

select-window -t monitor:system
