###########
# General #
###########

# Set default command so zsh is loaded by default
set -g default-command /bin/zsh

# Enable mouse support
set -g mouse on

# Start indexes at 1
set -g base-index 1
setw -g pane-base-index 1

# Suppress auto-rename
set-option -g allow-rename off

# Fix slow escape time
set -g escape-time 0

# Properly report focus events
set -g focus-events 1

# Support extended keys
set -g extended-keys on
set -g extended-keys-format csi-u

#########
# Style #
#########

# Status bar config
set -g window-status-format '#{?client_prefix,#[fg=black]#I:#W,#[fg=default]#I:#W}'
set -g window-status-current-format '#{?client_prefix,#[fg=green]#[bg=black]#[bright] #I:#W ,#[fg=black]#[bg=green]#[bright] #I:#W }'

set -g status-position bottom 
set -g status-style '#{?client_prefix,bg=green,bg=default}'
set -g status-left '#{?client_prefix,#[fg=black]#[bold][session: #S] ,#[fg=default]#[nobold][session: #S] }'
set -g status-left-length 30
set -g status-right '#{?client_prefix,#[fg=black]#[bold]waiting...,#[fg=default]#[nobold]%H:%M %d-%b}'

# Pane status bar
set -g pane-border-status top
set -g pane-border-format '#[bold]#{pane_index} #{pane_current_path}#[default]'

#######################
# Custom key bindings #
#######################

# vi key bindings
set -g mode-keys vi
set -g status-keys vi

# Reload config
bind-key r command-prompt -I "source-file ~/.tmux.conf"

# Custom prefix keys
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Better split commands
unbind '"'
bind '"' split-window -h

unbind %
bind % split-window -v

# Shift panes easier
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

###########
# Plugins #
###########

#  tmux-resurrect settings
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

# Add plugins here and use <prefix + I> to install! (Probably need to re-source with tmux `source ~/.tmux.conf`)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this at the bottom of the config)
run '~/.tmux/plugins/tpm/tpm'

