general {
	hide_cursor = true
	ignore_empty_input = true
}

background {
	monitor =
	path = ~/Photos/duga_radar.jpg
	blur_passes = 2
	blur_size = 7
}

input-field {
	monitor =
	placeholder_text = Hello $USER
	size = 20%, 5%
	outline_thickness = 1
	inner_color = rgba(0, 0, 0, 0.0)

	outer_color = rgba(200, 200, 200, 0.9) rgba(230, 230, 230, 0.9) 45deg
	check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
	fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg
	capslock_color = rgba(ff6633ee)

	font_color = rgb(143, 143, 143)
	rounding = 5

	fade_on_empty = false

	position = 0, 0
	halign = center
	valign = center
}

